version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.5
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build Docker Image
          command: |
            docker build -t menglewis/docker_test .
            docker run menglewis/docker_test /bin/bash -c "echo BUILD OK"
      - run:
          name: Build Package List
          command: |
            docker run menglewis/docker_test /bin/bash -c "pip freeze" > requirements.txt
      - store_artifacts:
          path: requirements.txt
