version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.5
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build Docker Image
          command: |
            docker build -t menglewis/docker_test .
            docker run menglewis/docker_test /bin/bash -c "echo BUILD OK"
      - run:
          name: Build Package List
          command: |
            docker run menglewis/docker_test /bin/bash -c "pip freeze" > requirements.txt
      - store_artifacts:
          path: requirements.txt
      - save_cache:
          key: requirements-{{ .Revision }}
          paths:
            - requirements.txt
  release:
    docker:
      - image: circleci/golang:1.8.1
    steps:
      - checkout
      - restore_cache:
          keys:
            - requirements-{{ .Revision }}
      - run:
          name: Install ghr
          command: |
            go get github.com/tcnksm/ghr
      - deploy:
          name: Create Github Release
          command: |
            ghr -t $GITHUB_TOKEN -u $CIRCLE_PROJECT_USERNAME -r $CIRCLE_PROJECT_REPONAME --replace `git describe --tags` requirements.txt

workflows:
  version: 2
  build_and_release:
    jobs:
      - build:
          filters:
            tags:
              only: /.*/
      - release:
          requires:
            - build
          filters:
            tags:
              only: /(?:0|[1-9]\d*)\.(?:0|[1-9]\d*)\.(?:0|[1-9]\d*)/
            branches:
              ignore: /.*/
